version: '3'
services:
  usuarios-mysql:
   container_name: usuarios-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: usuarios
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_ROOT_HOST: '%'
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql123
   ports:
   - "3306:3306"
   restart: always
  
  usuarios-app:
    restart: always
    build: ./usuarios
    working_dir: /usuarios
    ports:
    - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://usuarios-mysql:3306/usuarios?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql123
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      USUARIOS_TOPIC: topic_usuarios
    depends_on:
      - usuarios-mysql
      - kafka
  
  kafka:
    image: spotify/kafka:latest
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic topic_usuarios
      && 
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 2
      --topic topic_pedidos &) && (supervisord -n)"