version: '3'
services:
  usuarios-mysql:
   container_name: usuarios-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: usuarios
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_ROOT_HOST: '%'
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql123
   ports:
   - "3306:3306"
   restart: always
  
  usuarios-app:
    restart: always
    build: ./usuarios
    working_dir: /usuarios
    ports:
    - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://usuarios-mysql:3306/usuarios?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql123     
    depends_on:
      - usuarios-mysql